[package]
name = "li_installer"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/li_installer.rs"

[[bin]]
name = "li_installer_installation_probe"
path = "src/bin/li_installer_installation_probe.rs"

[[bin]]
name = "li_installer_dependency_manager"
path = "src/bin/li_installer_dependency_manager.rs"
