# SPDX-License-Identifier: AGPL-3.0-only
"""Minimal valid argument vectors for every CLI leaf."""

from __future__ import annotations


CLI_CASES = {
    "setup": ("setup",),
    "node.status": ("node", "status"),
    "node.move": ("node", "move"),
    "topology.show": ("topology", "show"),
    "topology.probe": (
        "topology", "probe", "left", "right", "--left-interface", "eth0",
        "--right-interface", "eth0", "--kind", "ethernet",
    ),
    "topology.plan": ("topology", "plan", "model"),
    "child.list": ("child", "list"),
    "child.prepare": ("child", "prepare"),
    "child.join": (
        "child", "join", "https://main.invalid", "--invite", "invite",
        "--main-certificate-sha256", "a" * 64,
    ),
    "child.invite": ("child", "invite", "--mode", "lan"),
    "child.approve": ("child", "approve", "child", "123456"),
    "child.sync": ("child", "sync"),
    "child.drain": ("child", "drain", "child"),
    "child.resume": ("child", "resume", "child"),
    "child.remove": ("child", "remove", "child"),
    "alias.list": ("alias", "list"),
    "alias.set": ("alias", "set", "fast", "model"),
    "alias.remove": ("alias", "remove", "fast"),
    "hardware": ("hardware",),
    "update": ("update", "--version", "1.2.3"),
    "update.check": ("update", "check", "--json"),
    "runtimes": ("runtimes",),
    "list": ("list",),
    "pack": ("pack", "runtime", "--output", "runtime.letsinfer"),
    "inspect": ("inspect", "runtime"),
    "upgrade": ("upgrade", "runtime", "--dry-run"),
    "rollback": ("rollback", "runtime", "--dry-run"),
    "verify": ("verify", "model", "--source-only"),
    "acquire": ("acquire", "model"),
    "benchmark": ("benchmark", "model", "--list"),
    "install": ("install", "model", "--no-service", "--no-start"),
    "scale": ("scale", "model", "--replicas", "2"),
    "serve": ("serve", "model", "--dry-run"),
    "status": ("status", "--json"),
    "doctor": ("doctor", "--json"),
    "logs": ("logs", "--tail", "0"),
    "start": ("start",),
    "restart": ("restart",),
    "recover": ("recover",),
    "exposure.status": ("exposure", "--json"),
    "expose": ("expose", "--json"),
    "unexpose": ("unexpose", "--json"),
    "pair": ("pair", "--timeout", "1"),
    "controllers.list": ("controllers", "list", "--json"),
    "controllers.forget": ("controllers", "forget", "controller", "--json"),
    "key.create": ("key", "create", "application", "--json"),
    "key.list": ("key", "list", "--json"),
    "key.show": ("key", "show", "key", "--json"),
    "key.rotate": ("key", "rotate", "key", "--json"),
    "key.revoke": ("key", "revoke", "key", "--json"),
    "key.policy": ("key", "policy", "key", "--json"),
    "audit.list": ("audit", "list", "--json"),
    "audit.show": ("audit", "show", "1", "--json"),
    "audit.verify": ("audit", "verify", "--json"),
    "audit.export": ("audit", "export", "--output", "audit.json"),
    "stop": ("stop",),
    "uninstall": ("uninstall",),
    "service-start": ("service-start", "--config", "service.json"),
    "service-stop": ("service-stop", "--config", "service.json"),
    "gateway": ("gateway", "--telemetry-file", "telemetry.json"),
    "node-agent": ("node-agent",),
    "core-rebind": ("core-rebind",),
    "core-prune": ("core-prune", "--dry-run", "--json"),
}
